### ISSUE TITLE
Message definition subscribed by rh_p12_pn_manager

### ISSUE THREAD

**Issue by shiba-8ro** [ROBOTIS-GIT/RH-P12-RN-A#2]
Should I use Message definition in the below image, when I publish a message to rh_p12_pn_manager?
![image](https://user-images.githubusercontent.com/5852451/130641716-4289131f-594b-4838-ba1e-e9f74e172993.png)

If it succeeds, I can command Goal Position of RH-P12-RN.
Is there a way if I want to command Goal Current?

**Comment by ROBOTIS-Will** [comment]
Hi @ROBOTIS-Shibata 
The base module that runs the RH-P12-RN manager package only has a subscriber implementation of setPosition.
In order to update the Goal Current, a relative subscriber has to be created.

**Comment by shiba-8ro** [comment]
Thank you for your reply. I close this issue.
